import { getFlickrImage } from "./placeholder-images";
import type { PropertyData } from "@/components/ui/PropertyCard";

export const MOCK_PROPERTIES: PropertyData[] = [
  {
    slug: "casa-moderna-3-dormitorios",
    name: "Casa Moderna 3 Dormitorios",
    description: "Amplia casa con jardín, cochera doble y quincho. Barrio residencial tranquilo.",
    price: 180000,
    currency: "USD",
    operation: "Venta",
    bedrooms: 3,
    bathrooms: 2,
    area: 180,
    imageUrl: getFlickrImage("casa", 800, 600, 3),
    badge: "Destacada",
  },
  {
    slug: "departamento-luminoso-centro",
    name: "Departamento Luminoso · Centro",
    description: "Piso alto con vista panorámica. Cocina integrada, balcón corrido, edificio con amenities.",
    price: 95000,
    currency: "USD",
    operation: "Venta",
    bedrooms: 2,
    bathrooms: 1,
    area: 72,
    imageUrl: getFlickrImage("departamento", 800, 600, 5),
  },
  {
    slug: "casa-en-country",
    name: "Casa en Country El Bosque",
    description: "Chalet en barrio privado. Seguridad 24hs, club house, canchas de tenis y pileta.",
    price: 320000,
    currency: "USD",
    operation: "Venta",
    bedrooms: 4,
    bathrooms: 3,
    area: 280,
    imageUrl: getFlickrImage("country", 800, 600, 11),
    badge: "Premium",
  },
  {
    slug: "terreno-esquina-comercial",
    name: "Terreno en Esquina · Zona Comercial",
    description: "Lote de 400 m² en esquina. Apto usos comerciales y residenciales. Todos los servicios.",
    price: 45000,
    currency: "USD",
    operation: "Venta",
    area: 400,
    imageUrl: getFlickrImage("terreno", 800, 600, 8),
  },
  {
    slug: "duplex-barrio-privado",
    name: "Dúplex en Barrio Privado",
    description: "Diseño contemporáneo, materiales de primera. Jardín privado y cochera cubierta.",
    price: 1800,
    currency: "USD",
    operation: "Alquiler",
    bedrooms: 3,
    bathrooms: 2,
    area: 140,
    imageUrl: getFlickrImage("duplex", 800, 600, 14),
  },
  {
    slug: "local-comercial-avenida",
    name: "Local Comercial en Avenida",
    description: "Planta baja con frente de 8 metros. Alta visibilidad y flujo peatonal. Baño incluido.",
    price: 600,
    currency: "USD",
    operation: "Alquiler",
    area: 60,
    imageUrl: getFlickrImage("local", 800, 600, 2),
  },
];

export const FEATURED_PROPERTIES = MOCK_PROPERTIES.slice(0, 3);
